#!/bin/sh

#Command specific to products-simple.csv; brand column 2 
#delimiter chracter "|" f = column 2 
#iconv to remove diacritics
#tr to convert capitlized letter to lowercase 
# > to output to desired "filename"

cut -d "|" -f 2| iconv -c -f utf-8 -t ascii |tr A-Z a-z|sort | uniq >
